name: Publish Retype powered website to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  actions: write
  contents: write
  deployments: write
  pull-requests: write

jobs:
  publish:
    name: Publish to retype branch

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: retypeapp/action-build@latest
        with:
          license: ${{ secrets.RETYPE_SECRET }}

      - uses: retypeapp/action-github-pages@latest
        with:
          branch: retype
          update-branch: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
